version: '3'
services:
  functions:
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"
      AzureWebJobsStorage: "${AZURE_STORAGE_CONNECTION_STRING}"
      AzureWebJobsDashboard: "${AZURE_STORAGE_CONNECTION_STRING}"
      SQL_SERVER: "sqldb"
    build: ./func-consumption
    container_name: mtc_funcs
    ports:
    - "8080:80"
    depends_on:
    - sqldb
    links:
    - sqldb
