version: '3'
services:
  admin-app:
    build: ./admin
    container_name: mtc_admin
    ports:
    - "3001:3001"
    environment:
      SQL_SERVER: "sqldb"
      MIGRATE: 1
    depends_on:
    - sqldb
    links:
    - sqldb
  check-submission:
    build: ./check-submission
    container_name: mtc_check_submission
    ports:
    - "3005:3005"
    environment:
      SQL_SERVER: "sqldb"
    depends_on:
    - sqldb
    links:
    - sqldb
  pupil-app:
    build:
      context: ./pupil-spa
      args:
        api_url: http://admin-app:3001
        check_submission_url: http://admin-app:3001/api/completed-check
        # check_submission_url: http://check-submission:3005/submit
    container_name: mtc_pupil
    ports:
    - "80:80"
    depends_on:
    - admin-app
    - check-submission
    links:
    - admin-app
    - check-submission
  admin-tests:
    build: ./test/admin
    container_name: admin_tests
    depends_on:
    - sqldb
    - admin-app
    volumes:
    - ./test-output/admin/screenshots:/usr/src/app/screenshots
    - ./test-output/admin/reports:/usr/src/app/reports
    links:
    - sqldb
    - admin-app
    environment:
      BASE_URL: "http://admin-app:3001"
      SQL_SERVER: "sqldb"
  pupil-tests:
    build: ./test/pupil
    container_name: pupil_tests
    depends_on:
    - pupil-app
    - sqldb
    - admin-app
    links:
    - pupil-app
    - sqldb
    volumes:
    - ./test-output/pupil/screenshots:/usr/src/app/screenshots
    - ./test-output/pupil/reports:/usr/src/app/reports
    environment:
      BASE_URL: "http://pupil-app"
      SQL_SERVER: "sqldb"
      