version: '3'
services:
  rabbit:
    image: "rabbitmq"
    container_name: rabbit
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - "$PWD/rabbitmq/data/log:/data/log"
    - "$PWD/rabbitmq/data/mnesia:/data/mnesia"
  node:
    build: ./client
    container_name: node
    ports:
    - "3001:3001"
    depends_on:
    - rabbit
    links:
    - rabbit